# Tell MetalLB what IP address range it can use
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  # Only using a single address for my network
  - 192.168.1.50-192.168.1.50

---

# Tell MetalLB to advertise it's IP addresses on the local network.
# This means it will answer ARP requests for the IP addresses in the pool 
# without needing to configure those IP addresses on the nodes themselves.
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system